parameters:
#    publicaciones.example.class: CAII\PublicacionesBundle\Example

services:
#    publicaciones.example:
#        class: %publicaciones.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]