noticias:
    pattern:  /{_locale}/noticias
    defaults: { _controller: NoticiaBundle:Noticia:index }

_noticias:
    pattern: /{_locale}/noticias/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: noticia}

noticia_new:
    pattern:  /admin/noticias/new
    defaults: { _controller: NoticiaBundle:Noticia:new }

noticia_edit:
    pattern:  /admin/noticias/edit/{id}
    defaults: { _controller: NoticiaBundle:Noticia:edit }

noticia_show:
    pattern:  /admin/noticias/show/{id}
    defaults: { _controller: NoticiaBundle:Noticia:show }

noticia_create:
    pattern:  /admin/noticias/create/
    defaults: { _controller: NoticiaBundle:Noticia:create }

noticia_update:
    pattern:  /admin/noticias/update/{id}
    defaults: { _controller: NoticiaBundle:Noticia:update }

noticia_delete:
    pattern:  /admin/noticias/delete/{id}
    defaults: { _controller: NoticiaBundle:Noticia:delete}

noticia_delete_viejas:
    pattern:  /admin/noticias/viejas
    defaults: { _controller: NoticiaBundle:Noticia:deleteNoticiasViejas}

noticia_backend:
    pattern:  /admin/noticia
    defaults: { _controller: NoticiaBundle:Noticia:indexBackend }

_noticia_backend:
    pattern: /admin/noticia/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: noticia_backend}

